<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="" href="/">
                <img class="logo" src="/assets/images/logo.png" alt="PHPCI">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/hosted-phpci">Hosted PHPCI</a></li>
                <li><a href="https://github.com/block8/phpci">PHPCI on Github</a></li>
                <li><a href="https://github.com/block8/phpci/issues">Issue Tracker</a></li>
                <li><a href="/news">News</a></li>
            </ul>                    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>