<div class="jumbotron">
    <p class="lead">
        Free and open source continuous integration specifically designed for PHP.

    </p>
    <a class="btn btn-large btn-success" href="https://github.com/icqparty/linebuild/releases">Download <span class="hidden-md">LINEBUILD 1.2.0</span> free</a>
    <a class="btn btn-large btn-success" href="#">sign up for hosted version</a>
</div>

<hr>

<div class="row-fluid marketing">
    <div class="span6">
        <h4>Subheading</h4>
        <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

        <h4>Subheading</h4>
        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

        <h4>Subheading</h4>
        <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>

    <div class="span6">
        <h4>Subheading</h4>
        <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

        <h4>Subheading</h4>
        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

        <h4>Subheading</h4>
        <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
</div>